build:
  environment:
    php:
      version: 8.2, 8.3, 8.4, 8.5
  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=build/logs/clover.xml'
        coverage:
          file: 'build/logs/clover.xml'
          format: 'clover'
